# Teamserver config
# The teamserver uses this config file to get up listeners and ports

database:
  uri: "localhost"
  port: "5432"
  dbuser: "hivemind"
  password: "changeme123"
  sslmode: "disable"

restapi:
  port: "4321"

# Users to be added to the database at startup
# Permissions:
#   1 = admin
#   2 = redteam operator
#   3 = spectator
users:
  - username: admin
    password: admin
    permission: "1"

# For more than one of the same type of listener on a different port, just add one
# as the example commented out below does
listeners:
  - tcp:
      enabled: "true"
      port: "1234"
  # Example of adding another TCP listener on a different port
  # - tcp:
  #     enabled: "true"
  #     port: "12345"
  # - udp:
  #     enabled: "false"
  #     port: "0"